// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeraConexion.Models;

#nullable disable

namespace PrimeraConexion.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20231029002311_PrimeraMigracion")]
    partial class PrimeraMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PrimeraConexion.Models.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TienePelo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TipoMascota")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdMascota");

                    b.ToTable("Mascotas");
                });
#pragma warning restore 612, 618
        }
    }
}
